### ISSUE TITLE
Group withou members?

### ISSUE THREAD

**Issue by imperalernest** [parusniksocial/sitetest1#2]
Group system withou members? What?

**Comment by RomanZSeldinov** [comment]
Hi, Ernest. Group system is beta product

**Comment by imperalernest** [comment]
And what?

**Comment by RomanZSeldinov** [comment]
Ernest, [link to Sitetest1 without beta group system](https://github.com/vpboxuser/parusnik-test1)

**Comment by imperalernest** [comment]
Thanks
